[tool.ruff]
extend-select = ["D"]
ignore = [
    "D105",   # Missing docstring in magic method
    "D107",   # Missing docstring in __init__
    "D203",   # One blank line required before class docstring (conflicts with Black)
    "D212",   # Multi-line docstring summary should start at first line (conflicts with D213)
]